-- IB-2128: USR_AUTH TABLE
CREATE TABLE USR_AUTH (
    SBJ_ID      text    CONSTRAINT USR_AUTH_SBJ_ID_PK PRIMARY KEY,
    LST_AUTH_ON bigint  NOT NULL
);
CREATE INDEX USR_AUTH_LST_AUTH_ON ON USR_AUTH(LST_AUTH_ON);
