-- IB-1710

ALTER TABLE USR_TTP ADD COLUMN LST_CNT INT8;

-- IB-2585 / IB-2586

ALTER TABLE FED_ACC DROP CONSTRAINT FED_ACC_SID_PK;
ALTER TABLE FED_ACC ADD PRIMARY KEY(SID, SBJ_ID, FP_KEY);

UPDATE FED_ACC fa SET SID = REPLACE(fa.SID, fa.FP_KEY || ':', '');

INSERT INTO BLITZ_SCHEMA_VERSION (SCRIPT_NAME, DATE) VALUES ('016-5.13.0.sql', LOCALTIMESTAMP(2));
