-- #2726

alter table RAD_STE
ADD COLUMN CLT_PORT bigint NULL,
ADD COLUMN REQ_ID bigint NULL,
ADD COLUMN REQ_AUTH text NULL,
ADD COLUMN PAS_ATRS text;

INSERT INTO BLITZ_SCHEMA_VERSION (SCRIPT_NAME, DATE) VALUES ('021-5.21.0.sql', LOCALTIMESTAMP(2));
