-- #3031

CREATE TABLE PSH_PNT (
    PRD text NOT NULL,
    USR_ID text NOT NULL,
    DAT text,
    LOC text NOT NULL,
    CLI_ID text NOT NULL,
    CRT_ON bigint NOT NULL,
    PRIMARY KEY(USR_ID, CLI_ID)
);

-- #3065

DROP INDEX IDX_FED_ACC_SBJ_ID;
CREATE INDEX IDX_FED_ACC_SBJ_ID ON FED_ACC(SBJ_ID);

INSERT INTO BLITZ_SCHEMA_VERSION (SCRIPT_NAME, DATE) VALUES ('023-5.26.0.sql', LOCALTIMESTAMP(2));
