-- #3138
ALTER TABLE CLT
    ADD COLUMN INS_ID TEXT;

ALTER TABLE RFR_TKN
    ADD COLUMN INS_ID TEXT;

-- #3122
ALTER TABLE ACS_TKN
    ADD COLUMN RIGHTS TEXT[];

INSERT INTO BLITZ_SCHEMA_VERSION (SCRIPT_NAME, DATE) VALUES ('025-5.28.0.sql', LOCALTIMESTAMP(2));
