services:
  memcached:
    image: memcached:latest
    container_name: memcached
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      - blitz-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./blitz-config:/etc/blitz-config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/static_errors:/usr/share/nginx/html/static_errors
      - ./logs:/var/log/nginx
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      blitz-net:
        aliases:
          - blitz-demo.loc

  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./postgresql/001-init-database.sql:/docker-entrypoint-initdb.d/001-init-database.sql
      - ./postgresql/002-new_pp_columns.sql:/docker-entrypoint-initdb.d/002-new_pp_columns.sql
      - ./postgresql/003-usd_id_table.sql:/docker-entrypoint-initdb.d/003-usd_id_table.sql
      - ./postgresql/004-usr_auth_table.sql:/docker-entrypoint-initdb.d/004-usr_auth_table.sql
      - ./postgresql/005-usr_agt_table.sql:/docker-entrypoint-initdb.d/005-usr_agt_table.sql
      - ./postgresql/006-usr_htp_hmc_alg.sql:/docker-entrypoint-initdb.d/006-usr_htp_hmc_alg.sql
      - ./postgresql/007-usr_atr_cfm.sql:/docker-entrypoint-initdb.d/007-usr_atr_cfm.sql
      - ./postgresql/008-wak.sql:/docker-entrypoint-initdb.d/008-wak.sql
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_PASSWORD=blitz_db_pass
      - POSTGRES_USER=blitz
      - POSTGRES_DB=blitzdb
    networks:
      - blitz-net

  rabbitmq:
    image: rabbitmq:3.9.5-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - ./rabbitmq/:/etc/rabbitmq/
    environment:
      - TZ=Europe/Moscow
    networks:
      - blitz-net

  blitz-console:
    restart: unless-stopped
    image: reaxoft/blitz-console:5.6.0
    container_name: blitz-console
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./blitz-config:/usr/share/identityblitz/blitz-config
      - ./logs:/usr/share/identityblitz/logs
    depends_on:
      - memcached
      - postgres
      - rabbitmq
    networks:
      - blitz-net

  blitz-idp:
    restart: unless-stopped
    image: reaxoft/blitz-idp:5.6.0
    container_name: blitz-idp
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./blitz-config:/usr/share/identityblitz/blitz-config
      - ./logs:/usr/share/identityblitz/logs
    depends_on:
      - memcached
      - postgres
      - rabbitmq
    networks:
      - blitz-net

  blitz-reg:
    restart: unless-stopped
    image: reaxoft/blitz-registration:5.6.0
    container_name: blitz-reg
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./blitz-config:/usr/share/identityblitz/blitz-config
      - ./logs:/usr/share/identityblitz/logs
    depends_on:
      - memcached
      - postgres
      - rabbitmq
    networks:
      - blitz-net

  blitz-rec:
    restart: unless-stopped
    image: reaxoft/blitz-recovery:5.6.0
    container_name: blitz-rec
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./blitz-config:/usr/share/identityblitz/blitz-config
      - ./logs:/usr/share/identityblitz/logs
    depends_on:
      - memcached
      - postgres
      - rabbitmq
    networks:
      - blitz-net

volumes:
  pg-data:
  rabbitmq-data:

networks:
  blitz-net:
    driver: bridge
