services:
  memcached:
    image: memcached:latest
    container_name: memcached
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      - blitz-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./blitz-config:/etc/blitz-config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/static_errors:/usr/share/nginx/html/static_errors
      - ./nginx/test-services:/usr/share/nginx/html/test-services
      - ./logs:/var/log/nginx
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      blitz-net:
        aliases:
          - blitz-demo.loc
          - test.services.loc

  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./postgresql/000-service-tasks.sql:/docker-entrypoint-initdb.d/000-service-tasks.sql
      - ./postgresql/001-init-database.sql:/docker-entrypoint-initdb.d/001-init-database.sql
      - ./postgresql/002-new_pp_columns.sql:/docker-entrypoint-initdb.d/002-new_pp_columns.sql
      - ./postgresql/003-usd_id_table.sql:/docker-entrypoint-initdb.d/003-usd_id_table.sql
      - ./postgresql/004-usr_auth_table.sql:/docker-entrypoint-initdb.d/004-usr_auth_table.sql
      - ./postgresql/005-usr_agt_table.sql:/docker-entrypoint-initdb.d/005-usr_agt_table.sql
      - ./postgresql/006-usr_htp_hmc_alg.sql:/docker-entrypoint-initdb.d/006-usr_htp_hmc_alg.sql
      - ./postgresql/007-usr_atr_cfm.sql:/docker-entrypoint-initdb.d/007-usr_atr_cfm.sql
      - ./postgresql/008-wak.sql:/docker-entrypoint-initdb.d/008-wak.sql
      - ./postgresql/009-fix_pp_column.sql:/docker-entrypoint-initdb.d/009-fix_pp_column.sql
      - ./postgresql/010-add_usr_prp.sql:/docker-entrypoint-initdb.d/010-add_usr_prp.sql
      - ./postgresql/011-pp_audit.sql:/docker-entrypoint-initdb.d/011-pp_audit.sql
      - ./postgresql/012-geo_to_audit.sql:/docker-entrypoint-initdb.d/012-geo_to_audit.sql
      - ./postgresql/013-tasks.sql:/docker-entrypoint-initdb.d/013-tasks.sql
      - ./postgresql/014-sec_ch_ua.sql:/docker-entrypoint-initdb.d/014-sec_ch_ua.sql
      - ./postgresql/015-5.12.0.sql:/docker-entrypoint-initdb.d/015-5.12.0.sql
      - ./postgresql/016-5.13.0.sql:/docker-entrypoint-initdb.d/016-5.13.0.sql
      - ./postgresql/017-5.15.0.sql:/docker-entrypoint-initdb.d/017-5.15.0.sql
      - ./postgresql/018-5.17.0.sql:/docker-entrypoint-initdb.d/018-5.17.0.sql
      - ./postgresql/019-5.18.0.sql:/docker-entrypoint-initdb.d/019-5.18.0.sql
      - ./postgresql/099-test_data.sql:/docker-entrypoint-initdb.d/099-test_data.sql
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_PASSWORD=blitz_db_pass
      - POSTGRES_USER=blitz
      - POSTGRES_DB=blitzdb
    networks:
      - blitz-net

  blitz-console:
    restart: unless-stopped
    image: reaxoft/blitz-console:5.20.0
    container_name: blitz-console
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./blitz-config:/usr/share/identityblitz/blitz-config
      - ./logs:/usr/share/identityblitz/logs
    tmpfs:
      - /tmp
    depends_on:
      - memcached
      - postgres
    networks:
      - blitz-net

  blitz-idp:
    restart: unless-stopped
    image: reaxoft/blitz-idp:5.20.0
    container_name: blitz-idp
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./blitz-config:/usr/share/identityblitz/blitz-config
      - ./logs:/usr/share/identityblitz/logs
    tmpfs:
      - /tmp
    depends_on:
      - memcached
      - postgres
    networks:
      - blitz-net

  blitz-reg:
    restart: unless-stopped
    image: reaxoft/blitz-registration:5.20.0
    container_name: blitz-reg
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./blitz-config:/usr/share/identityblitz/blitz-config
      - ./logs:/usr/share/identityblitz/logs
    tmpfs:
      - /tmp
    depends_on:
      - memcached
      - postgres
    networks:
      - blitz-net

  blitz-rec:
    restart: unless-stopped
    image: reaxoft/blitz-recovery:5.20.0
    container_name: blitz-rec
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./blitz-config:/usr/share/identityblitz/blitz-config
      - ./logs:/usr/share/identityblitz/logs
    tmpfs:
      - /tmp
    depends_on:
      - memcached
      - postgres
    networks:
      - blitz-net

  blitz-keeper:
    restart: unless-stopped
    image: reaxoft/blitz-keeper:5.11.3
    container_name: blitz-keeper
    ports:
      - 9012:9012
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./blitz-keeper:/etc/blitz-keeper
      - ./logs:/var/log/identityblitz
      - ./blitz-keeper/blitz-keeper:/etc/default/blitz-keeper
    depends_on:
      - blitz-idp
    networks:
      - blitz-net

volumes:
  pg-data:

networks:
  blitz-net:
    driver: bridge
